services:
  caddy:
    image: ghcr.io/squirrelkiev/snoodles-caddy:master
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - /home/snoodle/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - irc-net

volumes:
  caddy_data:
  caddy_config:
networks:
  irc-net:
    external: true
