version: '3.8'

services:
  caddy:
    build:
      context: .
      dockerfile: Caddy-Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/snoodle/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - irc-net

volumes:
  caddy_data:
  caddy_config:
networks:
  irc-net:
    external: true
