version: '3.8'

services:
  dibari-onk:
    image: ghcr.io/squirrelkiev/dibaribotnew:main
    volumes:
      - botdata-onk:/data
    networks:
      default:
      seqnet:
    depends_on:
      - postgres
      - seq
      
  dibari-pub:
    image: ghcr.io/squirrelkiev/dibaribotnew:main
    volumes:
      - botdata-pub:/data
    networks:
      default:
      seqnet:
    depends_on:
      - postgres
      - seq

  dibari-renai:
    image: ghcr.io/squirrelkiev/dibaribotnew:main
    volumes:
      - botdata-renai:/data
    networks:
      default:
      seqnet:
    depends_on:
      - postgres
      - seq

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dibariuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    external: true
volumes:
  botdata-onk:
  botdata-pub:
  botdata-renai:
  pgdata:
networks:
  default:
  seqnet:
    external: true
