version: "3.8"

services:
  code-server:
    image: codercom/code-server:latest
    environment:
      - PORT=3000
    volumes:
      - code-config:/home/coder/.config
      - homer-assets:/home/coder/project
      
  homer:
    image: b4bz/homer
    volumes:
      - homer-assets:/www/assets
    networks:
      - scroobles
    environment:
      - INIT_ASSETS=1 # default

networks:
  scroobles:
    external: true
    name: scroobles

volumes:
  code-config:
  homer-assets: