version: '3.8'

services:
  seigen-onk:
    image: ghcr.io/squirrelkiev/seigen:main
    volumes:
      - botdata-onk:/data
    networks:
      default:
      seqnet:
    depends_on:
      - postgres
      - seq

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=botuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    external: true
volumes:
  botdata-onk:
  pgdata:
networks:
  default:
  seqnet:
    external: true
