version: '3.8'

services:
  seigen-onk:
    image: ghcr.io/squirrelkiev/seigen:main
    volumes:
      - botdata-onk:/data
    depends_on:
      - postgres
      - seq

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=botuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
      
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seqdata:/data
    ports:
      - "5341:80"

secrets:
  db_password:
    external: true
volumes:
  botdata-onk:
  pgdata:
  seqdata:
