version: '3.8'
services:
  znc:
    image: znc:latest
    ports:
      - "6501:6501"
    restart: always
    volumes:
      - zncdata:/znc-data
    networks:
      - irc-net
volumes:
  zncdata:
networks:
  irc-net:
    external: true
    
